/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    id("java")
    id("base")
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
    maven { setUrl("https://jitpack.io") } 
}

dependencies {


    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is used by the application.
    implementation(libs.guava)

    implementation("com.formdev:flatlaf:3.2")

    implementation("com.jfoenix:jfoenix:9.0.10")

    implementation("com.miglayout:miglayout-swing:5.3")
    
     implementation ("com.formdev:flatlaf-intellij-themes:3.2")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(21))
    }
}

application {
    // Define the main class for the application.
    mainClass.set("universitycoursemanagementsystem.Main")
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}








